add input
js-tasks-ru/htmlcss-20220616_t3131653 pull request #16
Opened 2022-07-09 15:30 UTC by t3131653

2022-07-09 15:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-07-09 19:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-09 20:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-10 09:44 UTC, GSemikozov requested changes

2022-07-10 09:44 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox-set {
1-15 - это не часть блока .checkbox, а просто лишнее украшательство, может удалить эту часть)

2022-07-10 09:44 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +	padding-bottom: 16px;
лишнее (если чтобы в сетке снизу был отступ - это реализуем на уровне сетки / родителя)

2022-07-10 09:44 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox:focus .checkbox__title {
checkbox__input

2022-07-10 09:44 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox:focus .checkbox__title {
ниже уже есть, эту часть можно удалить

2022-07-10 09:44 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox_disabled .checkbox__control {
`.checkbox__input:disabled~.checkbox__state .checkbox__control`

2022-07-10 09:44 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox_disabled .checkbox__icon {
и тут

2022-07-10 09:44 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox_disabled .checkbox__title {
и тут

2022-07-10 11:23 UTC, t3131653 commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox-set {
хорошо, удалим))

2022-07-10 11:33 UTC, t3131653 commented on 07-lection5/01-checkbox/checkbox.css
> +	padding-bottom: 16px;
делаем обертку для чекбоксов?

2022-07-10 11:33 UTC, t3131653 commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox:focus .checkbox__title {
ага, понятно

2022-07-10 11:33 UTC, t3131653 commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox_disabled .checkbox__control {
ок))

2022-07-10 11:33 UTC, t3131653 commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox_disabled .checkbox__icon {
ок

2022-07-10 11:34 UTC, t3131653 commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox_disabled .checkbox__title {
ок

2022-07-10 11:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-07-10 19:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-10 19:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-10 20:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-10 21:04 UTC, t3131653 commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox-set {
тогда title как самостоятельный блок получается?

2022-07-10 21:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-11 09:21 UTC, GSemikozov requested changes

2022-07-11 11:17 UTC, t3131653 commented on 07-lection5/01-checkbox/checkbox.css
> +.title {
ок

2022-07-11 14:06 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox-set {
можно, но - он здесь не нужен)
мы делаем только блок checkbox

2022-07-11 14:07 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +	padding-bottom: 16px;
здесь удалим padding-bottom и все. А если вдруг надо будет сделать сетку из чекбоксов - можно создать блок .checkbox-list

2022-07-12 19:56 UTC, t3131653 commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox-set {
ага, значит удаляем

2022-07-13 18:47 UTC, GSemikozov approved these changes

2022-07-13 18:47 UTC, merged