Tabs
js-tasks-ru/htmlcss-20220616_t3131653 pull request #19
Opened 2022-07-13 12:28 UTC by t3131653

2022-07-13 12:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-07-13 18:55 UTC, GSemikozov requested changes

2022-07-13 18:55 UTC, GSemikozov commented on 07-lection5/tabs/tabs.css
> +	padding: 50px;
точно по всем сторонам такой отступ?) в tabs__scroller и .tabs__content скорее всего надо бы использовать контейнер?

2022-07-13 18:55 UTC, GSemikozov commented on 07-lection5/tabs/tabs.css
> +	width: 120px;
такого рода изменения (причем скорее всего захотим анимировать) размера при изменении состояния родителя - это не оч хорошо, не должно быть жесткой привязки к размерам конкретного текстуального контента (в разных табах он разный, потом еще 100 раз поменяем, и параллельно еще 100 раз поменяем здесь ширину в css =))

2022-07-13 18:55 UTC, GSemikozov commented on 07-lection5/tabs/tabs.css
> +	width: 120px;
лучше как в примере демо-проекта

2022-07-13 18:55 UTC, GSemikozov commented on 07-lection5/tabs/tabs.css
> +#complex-tab:checked~.tabs__main .tabs__content_simple {
а вот в таких случаях можно просто display: none

2022-07-15 10:36 UTC, t3131653 commented on 07-lection5/tabs/tabs.css
> +	width: 120px;
ага, точно, можно же было просто 100% сделать

2022-07-15 11:24 UTC, t3131653 commented on 07-lection5/tabs/tabs.css
> +	padding: 50px;
ну да, только сверху 50px. Добавила контейнер

2022-07-15 19:44 UTC, GSemikozov submitted a review, later dismissed

2022-07-15 19:44 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-07-19 07:43 UTC, GSemikozov requested changes

2022-07-19 07:43 UTC, GSemikozov commented on 07-lection5/tabs/tabs.css
> +	padding-bottom: 30px;
лучше наверно сразу на уровне .tabs__main

2022-07-19 20:34 UTC, t3131653 commented on 07-lection5/tabs/tabs.css
> +	padding-bottom: 30px;
ок

2022-07-20 18:53 UTC, GSemikozov approved these changes

2022-07-20 18:53 UTC, merged