Main
js-tasks-ru/htmlcss-20220616_t3131653 pull request #21
Opened 2022-07-27 19:11 UTC by t3131653

2022-08-01 17:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-01 17:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-08-03 19:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-08-07 19:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-08-08 19:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-08-11 19:30 UTC, GSemikozov requested changes

2022-08-11 19:30 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.tooltip_preview {
тултип лучше через родителя пусть выравнивается по середине, не нужно абсолютом

2022-08-11 19:30 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__window_preview {
.modal_preview .modal__window

2022-08-11 19:30 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input_preview {
лучше через родителя (на уровне блока нельзя задавать марджины)

2022-08-11 19:30 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__field_preview {
здесь и ниже привязка к модификатору на уровне блока (если оставляем), не стоит каждому элементу задавать отдельные модификаторы - .input_preview .input__field

2022-08-22 17:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-23 19:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-08-24 15:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-08-24 17:19 UTC, t3131653 commented on 05-lection3/01-tooltip/tooltip.css
> +.tooltip_preview {
ок

2022-08-24 17:19 UTC, t3131653 commented on 07-lection5/04-input/input.css
> +.input_preview {
ну да, точно))

2022-08-24 17:20 UTC, t3131653 commented on 07-lection5/04-input/input.css
> +.input__field_preview {
поняла

2022-08-25 11:58 UTC, GSemikozov approved these changes

2022-08-25 11:58 UTC, merged