Accordeon
js-tasks-ru/htmlcss-20220616_t3131653 pull request #4
Opened 2022-06-26 08:42 UTC by t3131653

2022-06-26 08:42 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-26 09:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-26 09:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-26 10:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-26 10:22 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-26 19:29 UTC, GSemikozov requested changes

2022-06-26 19:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.btn--primary {
второй вариант реализации?)

2022-06-26 19:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.btn--primary {
вообще, кнопки делаем в другом ПР, тут не нужно было добавлять, дальше будут конфликты

2022-06-26 19:29 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +@import '../assets/css/main.css';
не нужно импортировать, эти стили доступны глобально

2022-06-26 19:29 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +	line-height: 150%;
лучше не в процентах, а например 1.5

2022-06-26 19:29 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +	margin: 20px;
марджины на уровне блока не задаем

2022-06-26 19:29 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +	width: 730px;
ширину и высоту лучше не фиксировать

2022-06-26 19:29 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +	border: 1px solid gray;
цвет должен соответствовать макету

2022-06-26 19:29 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +	color: #212429;
цвета проставляем из переменных

2022-06-26 19:29 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +summary::-webkit-details-marker {
если это не глобальные сбросы, тогда нужно использовать классы - .accordeon__title

2022-06-26 19:29 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +summary .marker {
.accordeon__title

2022-06-26 19:29 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +details[open] .marker {
у details должен быть класс

2022-06-26 19:29 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +details[open] .accordeon__text {
и тут

2022-06-26 19:29 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +summary .marker {
.marker - не подойдет, это должен быть элемент аккордиона, например .accordion__marker

2022-06-26 19:29 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +            <details>
верхний div можно удалить а класс переставить сюда (.accordeon__item)

2022-06-27 06:52 UTC, t3131653 commented on 03-lection1/02-accordion/accordion.css
> +	line-height: 150%;
Исправила

2022-06-27 06:52 UTC, t3131653 commented on 03-lection1/02-accordion/accordion.css
> +@import '../assets/css/main.css';
Ок, поняла

2022-06-27 06:53 UTC, t3131653 commented on 03-lection1/02-accordion/accordion.css
> +	width: 730px;
Просто удаляем?

2022-06-27 07:08 UTC, t3131653 commented on 03-lection1/02-accordion/accordion.css
> +	width: 730px;
Или задать max-width?

2022-06-27 07:09 UTC, t3131653 commented on 03-lection1/02-accordion/accordion.css
> +	margin: 20px;
Можно добавить элемент accordeon__margin с заданными отступами?

2022-06-27 07:12 UTC, t3131653 commented on 03-lection1/02-accordion/accordion.css
> +summary::-webkit-details-marker {
понятно

2022-06-27 07:20 UTC, t3131653 commented on 03-lection1/02-accordion/accordion.css
> +details[open] .marker {
понятно, добавила

2022-06-27 07:20 UTC, t3131653 commented on 03-lection1/02-accordion/accordion.css
> +details[open] .accordeon__text {
ок

2022-06-27 07:24 UTC, t3131653 commented on 03-lection1/01-button/button.css
> +.btn--primary {
Даже не знаю, как это получилось. Что можно с этим сделать?

2022-06-27 07:25 UTC, t3131653 commented on 03-lection1/02-accordion/index.html
> +            <details>
Не совсем понятно, сделать микс?

2022-06-27 07:37 UTC, t3131653 commented on 03-lection1/02-accordion/accordion.css
> +summary .marker {
не могу понять, где задавать класс маркеру. В html?

2022-06-27 07:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-27 07:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-27 08:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-27 17:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-28 06:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-28 06:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-28 06:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-28 19:48 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +	margin: 20px;
лишний враппер чтобы отталкиваться от границ самого аккордиона, а не внешних относительно него блоков? нет, так не нужно) марджины здесь вообще не нужны, это будет решаться на уровне родителя (того блока, куда будет встраивать данный), скорее всего через классы-миксы

2022-06-28 19:49 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +summary .marker {
сначала описать в css (.accordion__marker), а затем повесить этот класс на хтмл элемент, если такой имеется (`<div class="accordion__marker">`)

2022-06-28 19:50 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +            <details>
нужно так: `<details class="accordeon__item">`

2022-06-29 09:28 UTC, t3131653 commented on 03-lection1/01-button/button.css
> +.btn--primary {
Это хорошо)

2022-06-29 09:33 UTC, t3131653 commented on 03-lection1/02-accordion/accordion.css
> +	margin: 20px;
Тогда просто удаляю марджины

2022-06-29 09:34 UTC, t3131653 commented on 03-lection1/02-accordion/accordion.css
> +	width: 730px;
ок

2022-06-29 10:35 UTC, t3131653 commented on 03-lection1/02-accordion/accordion.css
> +summary .marker {
Сделала

2022-07-01 21:39 UTC, GSemikozov requested changes

2022-07-01 21:39 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +<<<<<<< HEAD
во Введении в самом низу есть тема как решать конфликты, с отдельными ссылками под конкретный редактор. Если коротко - чтобы решить такой конфликт, надо принять актуальную версию и сохранить файл

2022-07-01 21:39 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +<<<<<<< HEAD
и тут

2022-07-01 21:39 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +	border: 1px solid gray;
по-прежнему актуально

2022-07-01 21:39 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +	color: #212429;
и тут

2022-07-02 08:47 UTC, t3131653 commented on 03-lection1/01-button/button.css
> +<<<<<<< HEAD
Вроде сделала как там написано

2022-07-02 08:47 UTC, t3131653 commented on 03-lection1/01-button/index.html
> +<<<<<<< HEAD
тоже

2022-07-10 09:38 UTC, GSemikozov approved these changes

2022-07-10 09:38 UTC, merged