add tooltip
js-tasks-ru/htmlcss-20220616_t3131653 pull request #8
Opened 2022-06-29 15:06 UTC by t3131653

2022-06-29 15:29 UTC, GSemikozov requested changes

2022-06-29 15:29 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.tooltip-wrapper {
удалим

2022-06-30 09:33 UTC, t3131653 commented on 05-lection3/01-tooltip/tooltip.css
> +.tooltip-wrapper {
ок

2022-06-30 09:37 UTC, t3131653 commented on 05-lection3/01-tooltip/tooltip.css
> +	position: absolute;
как же расположить ее так, чтобы бабл появлялся сверху, как в макете?

2022-07-01 21:44 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +	position: absolute;
никак) располагать нужно сам бабл)
скорее речь о том, что когда вокруг нет никакого контента, иконка слишком близко к верхнему краю экрана и при наведении бабл не видно? в таком случае в странице с решением задачи прямо на body можно указать например padding-top: 100px

2022-07-02 10:40 UTC, t3131653 commented on 05-lection3/01-tooltip/tooltip.css
> +	position: absolute;
да, проблема была в этом. Добавила паддинги

2022-07-04 14:10 UTC, GSemikozov requested changes

2022-07-04 14:10 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.tooltip-wrapper {
весь этот элемент и стили для body надо удалить из файла и перенести в тег style хтмл страницы с решением

2022-07-04 14:10 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +	bottom:130%;
`bottom: calc(100% + 8px)`

2022-07-05 16:57 UTC, t3131653 commented on 05-lection3/01-tooltip/tooltip.css
> +	bottom:130%;
а, вот как надо было))

2022-07-10 09:36 UTC, GSemikozov requested changes

2022-07-10 09:36 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +	position: absolute;
было же правильно =)

2022-07-11 09:17 UTC, GSemikozov requested changes

2022-07-11 09:17 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +	left: 35px;
это неправильное позиционирование - там нужно расположить бабл четко по середине не привязываясь к его конкретным размерам, для этого надо просто раскомментировать то что ниже

2022-07-11 10:32 UTC, t3131653 commented on 05-lection3/01-tooltip/tooltip.css
> +	left: 35px;
Из предыдущего коммента: в таком случае в странице с решением задачи прямо на body можно указать например padding-top: 100px
Если так делаю - получается. Как по-другому позиционировать триггер, чтобы был сверху виден бабл?
Если честно, не доходит до меня((

2022-07-11 13:58 UTC, GSemikozov requested changes

2022-07-11 13:58 UTC, GSemikozov commented on 05-lection3/01-tooltip/index.html
> +<body>
имею в виду вот здесь padding-top: 100px

2022-07-12 18:10 UTC, t3131653 commented on 05-lection3/01-tooltip/tooltip.css
> +	left: 35px;
это понятно, в этом у меня и проблема, что нет другого контента))

2022-07-13 18:46 UTC, GSemikozov approved these changes

2022-07-13 18:46 UTC, merged